"""
Patch curated_journals_by_category.json with approximate Clarivate JIF values.
Values are from 2023 JCR (Journal Citation Reports) based on training data.
Run once: python patch_clarivate_if.py

Journals that are too new for JCR, not indexed, or where the value is uncertain
are given null.  Review and correct any values that look wrong.
"""

import json

# ---------------------------------------------------------------------------
# Approximate 2023 Clarivate JIF values (training-data knowledge).
# Keys must match the 'name' field in the JSON (case-insensitive lookup).
# ---------------------------------------------------------------------------
CLARIVATE_IF: dict[str, float | None] = {
    # ── Multidisciplinary / core chemistry ───────────────────────────────────
    "Nature":                                                  50.5,
    "Science":                                                 44.7,
    "Nature Communications":                                   14.7,
    "Science Advances":                                        13.6,
    "Proceedings of the National Academy of Sciences":         11.1,
    "Journal of the American Chemical Society":                14.5,
    "Angewandte Chemie International Edition":                 16.1,
    "Angewandte Chemie":                                       16.1,
    "Chemical Reviews":                                        46.9,
    "Chemical Society Reviews":                                46.2,
    "Nature Chemistry":                                        20.1,
    "Accounts of Chemical Research":                           16.4,
    "Nature Reviews Chemistry":                                46.6,
    "Chem":                                                    23.5,
    "ACS Central Science":                                     12.7,
    "Nature Chemical Engineering":                             15.0,
    "Communications Chemistry":                                 5.9,
    "Chemical Science":                                         8.4,
    "Advanced Science":                                        15.1,
    "Physical Chemistry Chemical Physics":                      3.3,
    "Journal of Physical Chemistry Letters":                    4.0,
    "Chemical Communications":                                  4.4,
    "RSC Advances":                                             3.9,
    "ACS Omega":                                                3.8,
    "Scientific Reports":                                       3.8,
    "iScience":                                                 5.8,
    "Cell Reports Physical Science":                            8.5,
    "Chem Catalysis":                                          11.5,
    "One Earth":                                               15.5,
    "Engineering":                                             10.1,
    "National Science Review":                                 20.6,
    "PNAS Nexus":                                               8.5,
    "Dalton Transactions":                                      3.5,
    "Organic Letters":                                          5.1,
    "Inorganic Chemistry":                                      4.6,
    "Journal of Organic Chemistry":                             3.3,
    "ChemPhysChem":                                             3.3,
    "Journal of Hazardous Materials":                          13.6,
    "Chemosphere":                                              8.1,
    "CCS Chemistry":                                            8.0,
    "Aggregate":                                               16.1,
    "Cell Chemical Biology":                                    8.1,

    # ── Biotechnology and Biomedical Engineering ─────────────────────────────
    "Nature Biotechnology":                                    46.9,
    "Nature Biomedical Engineering":                           27.7,
    "Biotechnology Advances":                                  14.2,
    "Bioactive Materials":                                     18.0,
    "Journal of Controlled Release":                           10.5,
    "Biomaterials":                                            14.0,
    "Acta Biomaterialia":                                       9.7,
    "Biosensors and Bioelectronics":                           12.6,
    "Advanced Healthcare Materials":                           10.0,
    "Biofabrication":                                           8.8,
    "Metabolic Engineering":                                    8.1,
    "Journal of Nanobiotechnology":                            10.2,
    "Biomacromolecules":                                        5.9,
    "Biomaterials Science":                                     6.6,
    "Microbial Cell Factories":                                 5.8,
    "Trends in Biotechnology":                                 14.3,
    "Trends in biotechnology":                                 14.3,
    "Applied Microbiology and Biotechnology":                   4.1,
    "Biotechnology and Bioengineering":                         3.5,
    "Lab on a Chip":                                            6.1,
    "ACS Synthetic Biology":                                    3.7,
    "Journal of Biotechnology":                                 4.1,
    "Bioconjugate Chemistry":                                   4.9,
    "Biochemical Engineering Journal":                          3.6,
    "Microbial Biotechnology":                                  4.1,
    "Plant Biotechnology Journal":                             13.8,
    "Frontiers in Bioengineering and Biotechnology":            5.7,
    "Computational and Structural Biotechnology Journal":       6.0,
    "Applied Biochemistry and Biotechnology":                   3.3,
    "Journal of Industrial Microbiology & Biotechnology":       3.6,
    "Biotechnology Journal":                                    3.0,
    "Biotechnology Progress":                                   2.6,
    "Journal of Chemical Technology & Biotechnology":           3.2,
    "International Journal of Pharmaceutics":                   5.7,
    "European Journal of Pharmaceutics and Biopharmaceutics":   4.5,
    "Pharmaceutical Research":                                  3.3,
    "Tissue Engineering Part A":                                3.5,
    "Journal of Biomedical Materials Research Part A":          3.8,
    "Bioprocess and Biosystems Engineering":                    3.4,
    "Enzyme and Microbial Technology":                          3.4,
    "Process Biochemistry":                                     3.5,
    "ACS Biomaterials Science & Engineering":                   5.8,
    "Drug Delivery":                                            6.5,
    "Drug Delivery and Translational Research":                 5.0,
    "Cell Systems":                                             8.8,
    "Molecular Systems Biology":                                8.5,
    "Pharmacological Research":                                 9.4,
    "mSystems":                                                 5.0,
    "Food and Bioproducts Processing":                          3.9,
    "Biotechnology and Applied Biochemistry":                   2.5,
    "Molecular Biotechnology":                                  3.1,

    # ── Electrochemical Engineering ───────────────────────────────────────────
    "Nature Energy":                                           60.9,
    "Energy & Environmental Science":                          32.4,
    "Advanced Energy Materials":                               24.4,
    "ACS Energy Letters":                                      22.0,
    "Nano-Micro Letters":                                      31.6,
    "Nano Energy":                                             17.6,
    "Energy Storage Materials":                                18.9,
    "Journal of Energy Chemistry":                             13.1,
    "Carbon Energy":                                           20.4,
    "Journal of Energy Storage":                                9.4,
    "Journal of Power Sources":                                 9.2,
    "International Journal of Hydrogen Energy":                 8.1,
    "Electrochimica Acta":                                      6.9,
    "Journal of The Electrochemical Society":                   3.1,
    "Electrochemistry Communications":                          4.6,
    "Journal of Electroanalytical Chemistry":                   4.6,
    "ChemElectroChem":                                          4.3,
    "Solid State Ionics":                                       2.9,
    "Electroanalysis":                                          2.8,
    "Journal of Applied Electrochemistry":                      3.2,
    "Journal of Solid State Electrochemistry":                  2.8,
    "Corrosion Science":                                        8.3,
    "ACS Applied Energy Materials":                             5.9,
    "ECS Journal of Solid State Science and Technology":        1.7,
    "Energy Conversion and Management":                         9.9,
    "ChemSusChem":                                              7.7,
    "Sustainable Energy & Fuels":                               4.0,
    "Energy Technology":                                        3.4,
    "Current Opinion in Electrochemistry":                      4.5,
    "Batteries & Supercaps":                                    3.8,
    "Battery Energy":                                           8.1,
    "Energy & Environmental Materials":                        16.6,
    "EcoMat":                                                  12.3,
    "Ionics":                                                   2.9,
    "Journal of Physics: Energy":                               5.3,
    "Batteries":                                                4.1,
    "Fuel Cells":                                               3.0,
    "Electrocatalysis":                                         2.8,
    "Materials Chemistry Frontiers":                            7.3,
    "npj Computational Materials":                             12.2,
    "Applied Surface Science":                                  6.7,
    "Journal of Materials Chemistry A":                        11.9,
    "International Journal of Electrochemical Science":         1.5,
    "npj Clean Energy":                                         7.0,
    "Energy and AI":                                            9.6,
    "Electrochemical Science Advances":                        None,   # too new
    "Journal of Electrochemical Science and Engineering":      None,   # too new

    # ── Nanotechnology for Advanced Materials ────────────────────────────────
    "Nature Nanotechnology":                                   39.3,
    "Nature Materials":                                        37.3,
    "Advanced Materials":                                      27.4,
    "ACS Nano":                                                17.1,
    "Nano Letters":                                             9.6,
    "Advanced Functional Materials":                           18.5,
    "Materials Today":                                         24.2,
    "Small":                                                   13.3,
    "ACS Applied Materials & Interfaces":                       8.3,
    "Carbon":                                                  10.9,
    "Nano Today":                                              13.2,
    "Chemistry of Materials":                                   7.2,
    "Nano Research":                                            9.9,
    "Nanoscale":                                                5.8,
    "Matter":                                                  19.1,
    "Materials Horizons":                                      12.2,
    "Small Methods":                                           12.4,
    "Advanced Optical Materials":                               8.0,
    "ACS Materials Letters":                                    9.2,
    "Nanoscale Horizons":                                      10.5,
    "2D Materials":                                             4.7,
    "Scripta Materialia":                                       6.1,
    "Applied Materials Today":                                  8.3,
    "Composites Part B: Engineering":                          13.1,
    "Composites Part B Engineering":                           13.1,
    "Nano Convergence":                                        10.1,
    "Acta Materialia":                                          9.4,
    "Journal of Materials Science":                             3.5,
    "Journal of Alloys and Compounds":                          6.2,
    "Ceramics International":                                   5.2,
    "Thin Solid Films":                                         2.1,
    "Surface and Coatings Technology":                          4.4,
    "Nanotechnology":                                           3.3,
    "Journal of Nanoparticle Research":                         2.9,
    "Physical Review Materials":                                3.5,
    "MRS Bulletin":                                             4.3,
    "npj Quantum Materials":                                    9.4,
    "Journal of Physical Chemistry C":                          3.3,
    "Materials Today Physics":                                  8.6,
    "FlatChem":                                                 5.2,
    "Composites Science and Technology":                        8.7,
    "Journal of Colloid and Interface Science":                 9.9,
    "ACS Applied Nano Materials":                               5.3,
    "Materials Today Nano":                                    10.2,
    "Advanced Materials Technologies":                          6.8,
    "npj 2D Materials and Applications":                        9.4,
    "Journal of the European Ceramic Society":                  4.8,
    "Environmental Science: Nano":                              7.7,
    "ACS Applied Electronic Materials":                         4.4,
    "Extreme Mechanics Letters":                                4.7,

    # ── Process Systems Engineering ───────────────────────────────────────────
    "AIChE Journal":                                            3.7,
    "Chemical Engineering Science":                             4.4,
    "Industrial & Engineering Chemistry Research":              3.9,
    "Computers & Chemical Engineering":                         4.4,
    "Chemical Engineering Research and Design":                 4.2,
    "Separation and Purification Technology":                   8.6,
    "Applied Energy":                                          11.2,
    "Energy":                                                   9.0,
    "Process Safety and Environmental Protection":              6.9,
    "Journal of Process Control":                               3.6,
    "Automatica":                                               6.4,
    "Chemical Engineering and Processing: Process Intensification": 4.3,
    "Control Engineering Practice":                             4.5,
    "ISA Transactions":                                         6.3,
    "Digital Chemical Engineering":                             3.5,
    "Computers & Operations Research":                          4.6,
    "International Journal of Production Economics":            9.8,
    "Computers & Industrial Engineering":                       7.9,
    "European Journal of Operational Research":                 6.4,
    "Applied Mathematical Modelling":                           5.0,
    "IEEE Transactions on Control Systems Technology":          5.4,
    "International Journal of Control":                         1.6,
    "Annual Reviews in Control":                                7.3,
    "Systems & Control Letters":                                2.4,
    "Chemical Engineering Communications":                      1.8,
    "Journal of Chemical Engineering of Japan":                 0.9,
    "Chinese Journal of Chemical Engineering":                  3.0,
    "Chemometrics and Intelligent Laboratory Systems":          3.7,
    "Journal of Industrial and Engineering Chemistry":          5.8,
    "Korean Journal of Chemical Engineering":                   2.2,
    "Asia-Pacific Journal of Chemical Engineering":             1.4,
    "Brazilian Journal of Chemical Engineering":                1.5,
    "Canadian Journal of Chemical Engineering":                 2.0,
    "Journal of Chemical & Engineering Data":                   2.1,
    "Engineering Optimization":                                 2.7,
    "Optimization and Engineering":                             2.1,
    "Optimal Control Applications and Methods":                 2.0,
    "Processes":                                                3.4,
    "International Journal of Chemical Reactor Engineering":    1.3,
    "Separation Science and Technology":                        2.3,
    "Journal of Cleaner Production":                           11.1,
    "The International Journal of Advanced Manufacturing Technology": 3.4,
    "Reaction Chemistry & Engineering":                         3.6,
    "Chemical Engineering & Technology":                        2.0,
    "Journal of Food Process Engineering":                      2.8,
    "Operations Research":                                      4.8,
    "Omega":                                                    6.6,
    "IISE Transactions":                                        2.4,
    "Green Chemical Engineering":                               6.1,
    "Chemical Engineering Journal Advances":                    5.0,

    # ── Soft Matter & Polymer Engineering ────────────────────────────────────
    "Progress in Polymer Science":                             32.1,
    "Macromolecules":                                           5.1,
    "Advanced Fiber Materials":                                16.0,
    "Carbohydrate Polymers":                                   10.7,
    "Journal of Membrane Science":                              8.4,
    "Advances in Colloid and Interface Science":               15.9,
    "Polymer Reviews":                                         11.4,
    "International Journal of Biological Macromolecules":       7.7,
    "Langmuir":                                                 3.7,
    "ACS Macro Letters":                                        5.0,
    "Polymer Degradation and Stability":                        6.5,
    "Polymer":                                                  4.6,
    "European Polymer Journal":                                 5.9,
    "Advanced Industrial and Engineering Polymer Research":    15.0,
    "Polymers":                                                 4.8,
    "Journal of Rheology":                                      3.6,
    "Soft Matter":                                              3.4,
    "Rheologica Acta":                                          2.0,
    "Macromolecular Rapid Communications":                      4.2,
    "Cellulose":                                                5.5,
    "Polymer Chemistry":                                        4.1,
    "ACS Applied Polymer Materials":                            5.0,
    "Colloids and Surfaces A":                                  5.6,
    "Polymer Testing":                                          5.4,
    "Polymer Composites":                                       4.2,
    "Journal of Non-Newtonian Fluid Mechanics":                 2.9,
    "Macromolecular Chemistry and Physics":                     2.1,
    "Polymer Engineering and Science":                          2.4,
    "Polymer Bulletin":                                         3.3,
    "Journal of Applied Polymer Science":                       2.9,
    "Polymer International":                                    2.9,
    "Polymer Journal":                                          2.6,
    "Reactive and Functional Polymers":                         4.2,
    "ACS Polymers Au":                                          5.0,
    "Giant":                                                    7.0,
    "Journal of Polymer Research":                              2.8,
    "Colloid & Polymer Science":                                2.4,
    "Liquid Crystals":                                          2.4,
    "Colloids and Surfaces B: Biointerfaces":                   5.4,
    "Journal of Polymers and the Environment":                  4.6,
    "Journal of Polymer Science":                               3.4,
    "Polymer-Plastics Technology and Materials":                4.3,
    "Carbohydrate Research":                                    2.7,
    "Journal of Polymer Engineering":                           1.8,
    "Macromolecular Research":                                  2.2,
    "International Journal of Polymer Science":                 2.1,
    "RSC Applied Polymers":                                    None,   # too new for JCR
    "Polymers from Renewable Resources":                       None,   # not indexed in JCR

    # ── Sustainable Reaction Engineering ─────────────────────────────────────
    "Nature Catalysis":                                        41.8,
    "Applied Catalysis B: Environmental":                      22.1,
    "ACS Catalysis":                                           12.9,
    "Renewable and Sustainable Energy Reviews":                17.1,
    "Nature Sustainability":                                   22.0,
    "Bioresource Technology":                                  11.4,
    "Catalysis Reviews":                                       14.2,
    "Journal of Catalysis":                                     6.5,
    "Fuel":                                                     7.7,
    "Catalysis Today":                                          5.9,
    "Applied Catalysis A: General":                             4.7,
    "Organic Process Research & Development":                   3.7,
    "Renewable Energy":                                         9.0,
    "Waste Management":                                         8.1,
    "ChemCatChem":                                              4.2,
    "Catalysis Science & Technology":                           4.5,
    "Energy & Fuels":                                           5.5,
    "Topics in Catalysis":                                      2.9,
    "Solar Energy":                                             6.7,
    "Solar Energy Materials and Solar Cells":                   6.9,
    "Resources, Conservation and Recycling":                   13.2,
    "Biomass and Bioenergy":                                    5.6,
    "Catalysis Communications":                                 3.9,
    "Fuel Processing Technology":                               5.5,
    "International Journal of Green Energy":                    3.5,
    "Journal of Environmental Chemical Engineering":            7.7,
    "Sustainable Energy Technologies and Assessments":          7.4,
    "SusMat":                                                  20.2,
    "Sustainable Production and Consumption":                  10.5,
    "Advanced Sustainable Systems":                             6.2,
    "Chinese Journal of Catalysis":                            15.7,
    "Waste Management & Research":                              3.5,
    "Environmental Science & Technology Letters":               9.5,
    "Green Energy & Environment":                              13.8,
    "Journal of CO2 Utilization":                               8.5,
    "Molecular Catalysis":                                      3.7,
    "Sustainable Chemistry and Pharmacy":                       6.5,
    "Journal of Analytical and Applied Pyrolysis":              5.6,
    "Combustion and Flame":                                     5.1,
    "Clean Technologies and Environmental Policy":              4.8,
    "Green Processing and Synthesis":                           3.2,
    "Environmental Science & Technology":                      11.4,
    "RSC Sustainability":                                      None,   # too new for JCR
    "Sustainable Energy & Fuels":                               4.0,

    # ── Previously unmatched ─────────────────────────────────────────────────
    "ACS Sustainable Chemistry & Engineering":                  8.4,
    "Applied Catalysis A General":                              4.7,
    "Applied Catalysis A: General":                             4.7,
    "Chinese Journal of Catalysis":                             15.7,
    "CHINESE JOURNAL OF CATALYSIS (CHINESE VERSION)":           15.7,
    "Chemical Engineering Journal":                             13.3,
    "Chemical Engineering and Processing - Process Intensification": 4.2,
    "Chemical Engineering and Processing: Process Intensification": 4.2,
    "Colloids and Surfaces A Physicochemical and Engineering Aspects": 5.0,
    "Colloids and Surfaces A: Physicochemical and Engineering Aspects": 5.0,
    "Colloids and Surfaces B Biointerfaces":                    5.4,
    "Colloids and Surfaces B: Biointerfaces":                   5.4,
    "Energy & Environment Materials":                           13.0,
    "Energy & environment materials":                           13.0,
    "Environmental Science: Nano":                              7.3,
    "Environmental Science Nano":                               7.3,
    "Green Chemistry":                                          9.8,
    "Journal of Physics: Energy":                               7.4,
    "Journal of Physics Energy":                                7.4,
    "Microsystems & Nanoengineering":                           7.3,
    "Resources, Conservation and Recycling":                    13.2,
    "Resources Conservation and Recycling":                     13.2,
    "Canadian Journal of Chemical Engineering":                  1.6,
    "The Canadian Journal of Chemical Engineering":              1.6,
    "Journal of Organic Chemistry":                              3.1,
    "The Journal of Organic Chemistry":                          3.1,
    "Journal of Physical Chemistry C":                           3.3,
    "The Journal of Physical Chemistry C":                       3.3,
    "Journal of Physical Chemistry Letters":                     4.2,
    "The Journal of Physical Chemistry Letters":                 4.2,
    "Waste Management & Research":                              3.5,
    "Waste Management & Research The Journal for a Sustainable Circular Economy": 3.5,
}

# ---------------------------------------------------------------------------

def normalise(name: str) -> str:
    return name.lower().strip()

lookup = {normalise(k): v for k, v in CLARIVATE_IF.items()}

with open("curated_journals_by_category.json", encoding="utf-8") as f:
    db = json.load(f)

matched = 0
unmatched = []

for category, journals in db.items():
    for j in journals:
        key = normalise(j["name"])
        if key in lookup:
            j["clarivate_if"] = lookup[key]
            matched += 1
        else:
            j["clarivate_if"] = None
            unmatched.append(j["name"])

with open("curated_journals_by_category.json", "w", encoding="utf-8") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Done.  Matched {matched} journals, {len(unmatched)} left as null:")
for name in sorted(set(unmatched)):
    print(f"  - {name}")
